[package]
name = "todo_cmd"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"

[lib]
name = "todolib"
path = "src/lib/mod.rs"
